name: flutter_sy_travel_animation
description: It is Flutter UI practice. I am watching the codes of some youtube channel and following it.Thank you

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

=
flutter:

  uses-material-design: true


  assets:
    - assets/
